### ISSUE TITLE
CAdvisor container crashes

### ISSUE THREAD

**Issue by biran0079** [wavefrontHQ/integrations#3]
With following log printed:
```
goroutine 78349 [sleep]:
time.Sleep(0x4c696cb6)
	/usr/local/go/src/runtime/time.go:59 +0xf9
github.com/google/cadvisor/manager.(*containerData).housekeeping(0xc4202b3c20)
	/opt/go/src/github.com/google/cadvisor/manager/container.go:457 +0x340
created by github.com/google/cadvisor/manager.(*containerData).Start
	/opt/go/src/github.com/google/cadvisor/manager/container.go:95 +0x3f
goroutine 78338 [select]:
github.com/google/cadvisor/container/common.(*realFsHandler).trackUsage(0xc4224c4090)
	/opt/go/src/github.com/google/cadvisor/container/common/fsHandler.go:115 +0x3f1
created by github.com/google/cadvisor/container/common.(*realFsHandler).Start
	/opt/go/src/github.com/google/cadvisor/container/common/fsHandler.go:138 +0x3f

goroutine 84437 [runnable]:
fmt.(*pp).printArg(0xc4200fa0c0, 0xbf1ae0, 0xc42319e790, 0x73)
	/usr/local/go/src/fmt/print.go:604 +0xa37
fmt.(*pp).doPrintf(0xc4200fa0c0, 0xd5005c, 0x2b, 0xc4233c5658, 0x8, 0x8)
	/usr/local/go/src/fmt/print.go:998 +0x11e7
fmt.Sprintf(0xd5005c, 0x2b, 0xc4233c5658, 0x8, 0x8, 0x2f, 0x6)
	/usr/local/go/src/fmt/print.go:196 +0x6a
github.com/google/cadvisor/storage/wavefront.(*wavefrontStorage).AddStats(0xc42022e1b0, 0xc42196363d, 0x40, 0xc421963635, 0x48, 0xc4216cb2c0, 0x2, 0x2, 0xd3098d, 0x6, ...)
	/opt/go/src/github.com/google/cadvisor/storage/wavefront/wavefront.go:273 +0x1135
github.com/google/cadvisor/cache/memory.(*InMemoryCache).AddStats(0xc420013c40, 0xc42196363d, 0x40, 0xc421963635, 0x48, 0xc4216cb2c0, 0x2, 0x2, 0xd3098d, 0x6, ...)
	/opt/go/src/github.com/google/cadvisor/cache/memory/memory.go:90 +0x113
github.com/google/cadvisor/manager.(*containerData).updateStats(0xc4237de000, 0x1, 0xc4207f7260)
	/opt/go/src/github.com/google/cadvisor/manager/container.go:566 +0x21f
github.com/google/cadvisor/manager.(*containerData).housekeepingTick(0xc4237de000)
	/opt/go/src/github.com/google/cadvisor/manager/container.go:466 +0x2f
github.com/google/cadvisor/manager.(*containerData).housekeeping(0xc4237de000)
	/opt/go/src/github.com/google/cadvisor/manager/container.go:417 +0x217
created by github.com/google/cadvisor/manager.(*containerData).Start
	/opt/go/src/github.com/google/cadvisor/manager/container.go:95 +0x3f``
```

**Comment by kentwang929** [comment]
Which version of cAdvisor image is this container and is this reproducible?

**Comment by biran0079** [comment]
I am using v0.25.

**Comment by kentwang929** [comment]
We have updated the cadvisor image to v0.26 recently.  Can you see if that fixes it for you?
